# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20171116_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
